    library(tidyr)
    library(dplyr)
    library(ggplot2)

# Plots CIs for the quantile

fullData_ConfidenceLowerBound = read.csv("../results/tradeoff/listener-curve-binomial-confidence-bound-quantile.tsv", sep="\t") %>% filter(Type != "GROUND")
fullData_ConfidenceLowerBound_05 = read.csv("../results/tradeoff/listener-curve-binomial-confidence-bound-quantile-05.tsv", sep="\t") %>% filter(Type != "GROUND")

fullData_BinomialTest = read.csv("../results/tradeoff/listener-curve-binomial-test.tsv", sep="\t") %>% filter(Type != "GROUND")

memListenerSurpPlot_onlyWordForms_boundedVocab = function(language) {
    data = fullData_ConfidenceLowerBound %>% filter(Language == language)
    data2 = fullData_BinomialTest %>% filter(Language == language)
    data3 = fullData_ConfidenceLowerBound_05 %>% filter(Language == language)
    #data = merge(data, data2, by=c("Language", "Position", "Type"))
    #data$Memory = data$Memory.x
    plot = ggplot(data, aes(x=Memory, y=LowerConfidenceBound, fill=Type, color=Type))
    plot = plot + geom_line(size=1, linetype="dotted") 
    plot = plot + geom_line(data=data3, size=2, linetype="dashed") 
    plot = plot + geom_line(data=data2, aes(x=Memory, y=BetterEmpirical), size=2)
    data2 = data2 %>% mutate(pValue_print = ifelse(round(pValue,5) == 0, "p<0.00001", paste("p=", round(pValue,5), sep="")))
    plot = plot + geom_text(data=data2 %>% filter(Position %% 9 == 0, Type == "REAL_REAL"), aes(x=Memory, y=BetterEmpirical+0.1, label=pValue_print), size=3)
    plot = plot + geom_text(data=data2 %>% filter(Position %% 9 == 0, Type == "GROUND"), aes(x=Memory, y=BetterEmpirical+0.05, label=pValue_print), size=3)
    plot = plot + theme_classic() 
    plot = plot + theme(legend.position="none") 
    plot = plot + ylim(0,1.1)
    plot = plot + ylab("Quantile")
    plot = plot + xlab("Memory")
    # + geom_line(aes(x=Memory, y=-MedianDiff_Upper))
    ggsave(plot, file=paste("figures/",language,"-listener-surprisal-memory-QUANTILES_onlyWordForms_boundedVocab_REAL.pdf", sep=""), height=3.5, width=4.5)
    return(plot)
}

plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Arabic")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Catalan")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Czech")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Dutch")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Finnish")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("French")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("German")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Hindi")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Norwegian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Spanish")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Basque")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Bulgarian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Croatian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Estonian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Hebrew")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Japanese")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Polish")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Romanian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Slovak")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Slovenian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Swedish")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Afrikaans")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Chinese")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Danish")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Greek")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Hungarian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Russian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Erzya-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("North_Sami")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Persian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Serbian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Turkish")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Ukrainian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Vietnamese")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Amharic-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Armenian-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Breton-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Buryat-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Cantonese-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Faroese-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Kazakh-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Kurmanji-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Naija-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Thai-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Uyghur-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Bambara-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Erzya-Adap")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Maltese")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Latvian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Indonesian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Urdu")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Portuguese")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("English")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Italian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Russian")
plot = memListenerSurpPlot_onlyWordForms_boundedVocab("Korean")



