* Phonemic, Heldout (SI)
 * forWords_Sesotho_OptimizeOrder_FormsWordsGraphemes_Prefixes_ByType_HeldoutClip.py
 * forWords_Sesotho_OptimizeOrder_FormsWordsGraphemes_Suffixes_ByType_HeldoutClip.py

* Phonemic, Naive (SI)
 * forWords_Sesotho_OptimizeOrder_FormsWordsGraphemes_Prefixes_ByType.py
 * forWords_Sesotho_OptimizeOrder_FormsWordsGraphemes_Suffixes_ByType.py

* Morphemic, Heldout (Main Paper)
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Prefixes_HeldoutClip.py
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Suffixes_HeldoutClip.py

* Morphemic, Naive (Main Paper)
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Prefixes.py
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Suffixes.py

* Control for Variationin Test Sets
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Prefixes_HeldoutClip_VarySets.py
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Suffixes_HeldoutClip_VarySets.py

* Other
 * forWords_Sesotho_OptimizeOrder_Normalized_ByType_Suffixes_HeldoutClip_AllOptions.py

